version: 2.1
orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5

jobs:
  test:
    docker:
      - image: cimg/node:16.14-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - cypress/install
      - cypress/run:
          command: npm run test
          store_artifacts: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - develop 